"""cria tabela veiculos

Revision ID: 6b7d41cd462d
Revises: d6d6d07e7b9f
Create Date: 2026-07-22 23:00:41.543658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b7d41cd462d'
down_revision: Union[str, Sequence[str], None] = 'd6d6d07e7b9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('veiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('marca', sa.String(length=50), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('cor', sa.String(length=30), nullable=True),
    sa.Column('observacoes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_veiculos_id'), 'veiculos', ['id'], unique=False)
    op.create_index(op.f('ix_veiculos_placa'), 'veiculos', ['placa'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_veiculos_placa'), table_name='veiculos')
    op.drop_index(op.f('ix_veiculos_id'), table_name='veiculos')
    op.drop_table('veiculos')
    # ### end Alembic commands ###
